# Generated by Django 5.2.4 on 2025-07-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("position", models.CharField(max_length=50)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date_joined", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                ("grade", models.CharField(max_length=10)),
                ("date_of_birth", models.DateField()),
                (
                    "fees_due",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "fees_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("date_joined", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
