# Generated by Django 5.2.4 on 2025-07-28 17:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name="staff",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="position",
        ),
        migrations.RemoveField(
            model_name="staff",
            name="salary",
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.AddField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("Teacher", "Teacher"),
                    ("Admin", "Admin"),
                    ("Support", "Support Staff"),
                ],
                default="Teacher",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="enrolled_on",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="staff",
            name="date_joined",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="fees_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="fees_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.grade"
            ),
        ),
    ]
