# Generated by Django 5.2.4 on 2025-07-28 21:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_activity_event_grade_notification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(auto_now_add=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("online", "Online Payment"),
                            ("card", "Card Payment"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["title"], "verbose_name_plural": "Activities"},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_date"]},
        ),
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-date_created"]},
        ),
        migrations.AlterModelOptions(
            name="staff",
            options={"ordering": ["name"], "verbose_name_plural": "Staff"},
        ),
        migrations.AlterModelOptions(
            name="student",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("club", "Club"),
                    ("sport", "Sport"),
                    ("academic", "Academic"),
                    ("volunteer", "Volunteer"),
                    ("arts", "Arts & Crafts"),
                    ("music", "Music"),
                    ("drama", "Drama"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="instructor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.staff",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="max_participants",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name="activity",
            name="schedule",
            field=models.CharField(
                blank=True, help_text="e.g., Mondays 3-4 PM", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.staff",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("sports", "Sports"),
                    ("cultural", "Cultural"),
                    ("meeting", "Meeting"),
                    ("holiday", "Holiday"),
                    ("exam", "Examination"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="target_grades",
            field=models.ManyToManyField(
                blank=True, help_text="Leave empty for all grades", to="pages.grade"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="capacity",
            field=models.PositiveIntegerField(
                default=30, help_text="Maximum students per grade"
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="grade",
            name="description",
            field=models.TextField(
                blank=True, help_text="Grade description or notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.staff",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_audience",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("students", "Students"),
                    ("staff", "Staff"),
                    ("parents", "Parents"),
                    ("grade_specific", "Grade Specific"),
                ],
                default="all",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_grade",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific grade if target is grade_specific",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.grade",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default="General Notification", max_length=200),
        ),
        migrations.AddField(
            model_name="staff",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="department",
            field=models.CharField(
                blank=True, help_text="e.g., Mathematics, Science, etc.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="staff",
            name="qualifications",
            field=models.TextField(
                blank=True, help_text="Educational qualifications and certifications"
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="staff_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated if empty",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="subjects",
            field=models.CharField(
                blank=True,
                help_text="Subjects taught (comma-separated)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("graduated", "Graduated"),
                    ("transferred", "Transferred"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated if empty",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="staff",
            name="date_joined",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="role",
            field=models.CharField(
                choices=[
                    ("Teacher", "Teacher"),
                    ("Admin", "Administrator"),
                    ("Support", "Support Staff"),
                    ("Principal", "Principal"),
                    ("Vice Principal", "Vice Principal"),
                    ("Counselor", "Counselor"),
                ],
                default="Teacher",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="fees_due",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="fees_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["role", "status"], name="pages_staff_role_8e94ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["staff_id"], name="pages_staff_staff_i_8fa53f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["grade", "status"], name="pages_stude_grade_i_a90e49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_id"], name="pages_stude_student_d85d8d_idx"
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.activity"
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pages.student"
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pages.staff",
            ),
        ),
        migrations.AddField(
            model_name="feepayment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="pages.student",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "student")},
        ),
    ]
